### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by techgamingcore**
NUH UH

### CODE REVIEW

**Comment by Andromeda-Galaxy29** [comment]
1. This is not how you install mods in mindustry. While you can do that, there is a much, much simpler way
2. Why mention that you need to have java when the game itself requires java in the first place
3. There is no "Create new game or load an existing one" in mindustry. There is only one save
4. Custom Sprites? Why is that section even there? Of course it has custom sprites

This entire file is written by a person who has never played the game

**Comment by techgamingcore** [comment]
go say this to chatgpt lol
image

**Comment by iRatzeyMezeri** [comment]
Did Chatgpt write this- oh wait lmfao

**Comment by Andromeda-Galaxy29** [comment]
That makes **so much** sense. Don't try to PR this repo again

**Comment by techgamingcore** [comment]
go cry abt it

**Pull request closed without merging**
