### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by techgamingcore**
Just a template. get some security u unsecure beings

### CODE REVIEW

**Comment by techgamingcore** [comment]
also i dint break any rules. ILLEGAL BANNNNNNNNNNNNNNNNNN

**Comment by Andromeda-Galaxy29** [comment]
Why? What security updates?

**Comment by Andromeda-Galaxy29** [comment]
And I am not unbanning you from the discord server

**Comment by techgamingcore** [comment]
i m stealing ur milk

**Pull request closed without merging**
